const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const ROOT=path.join(__dirname,'..'),SITE=path.join(ROOT,'site');const source=fs.readFileSync(path.join(SITE,'sw.js'),'utf8');
function sw(){const events={},deleted=[],added=[],network=[];let skips=0,claims=0;const cache={match:async u=>new Response('cached: '+u),addAll:async u=>added.push(...u)};
 const scope={location:{href:'https://example.test/arucon/sw.js'},addEventListener:(n,f)=>events[n]=f,skipWaiting:()=>{skips++},clients:{claim:async()=>{claims++}}};
 const prefix='arucon-mcheck:'+encodeURIComponent('/arucon/')+':';
 vm.runInNewContext(source,{URL,self:scope,caches:{open:async()=>cache,keys:async()=>[prefix+'old','unrelated-cache','arucon-mcheck:'+encodeURIComponent('/other/')+':old'],delete:async n=>deleted.push(n)},fetch:async r=>{network.push(r.url);return new Response('network')} });
 return{events,deleted,added,network,prefix,skips:()=>skips,claims:()=>claims,cache};}
async function lifecycle(s,name){let pending;s.events[name]({waitUntil:p=>pending=p});await pending;}
test('Manifest points at real same-origin icons and correct dimensions',()=>{const m=JSON.parse(fs.readFileSync(path.join(SITE,'manifest.webmanifest')));assert.equal(m.display,'standalone');assert.equal(m.start_url,'./');for(const i of m.icons){assert(fs.existsSync(path.join(SITE,i.src)));assert(!i.src.startsWith('https:'));const png=fs.readFileSync(path.join(SITE,i.src));assert.equal(png.readUInt32BE(16)+'x'+png.readUInt32BE(20),i.sizes);}});
test('Install caches exactly the self-contained page and icon resources',async()=>{const s=sw();await lifecycle(s,'install');assert.equal(s.added.length,7);assert(s.added.every(u=>u.startsWith('https://example.test/arucon/')));assert(s.added.some(u=>u.endsWith('index.html')))});
test('New worker waits instead of forcibly replacing a running interaction',async()=>{const s=sw();await lifecycle(s,'install');assert.equal(s.skips(),0);s.events.message({data:{type:'unrelated'}});assert.equal(s.skips(),0);s.events.message({data:{type:'ARUCON_ACTIVATE'}});assert.equal(s.skips(),1)});
test('Activation only cleans own prototype and scope caches',async()=>{const s=sw();await lifecycle(s,'activate');assert.deepEqual(s.deleted,[s.prefix+'old']);assert.equal(s.claims(),1)});
test('Cached navigation can be served offline in the worker fixture',async()=>{const s=sw();let answer;s.events.fetch({request:new Request('https://example.test/arucon/'),respondWith:p=>answer=p});assert(answer);assert.equal(await(await answer).text(),'cached: https://example.test/arucon/');assert.equal(s.network.length,0)});
test('Uncached known asset falls back to network only without state calculations',async()=>{const s=sw();s.cache.match=async()=>undefined;let answer;s.events.fetch({request:new Request('https://example.test/arucon/index.html'),respondWith:p=>answer=p});assert.equal(await(await answer).text(),'network');assert.equal(s.network.length,1)});
test('Third-party, POST and non-asset endpoints are not intercepted',()=>{for(const r of [new Request('https://elsewhere.test/'),new Request('https://example.test/arucon/api',{method:'POST'}),new Request('https://example.test/other/'),new Request('https://example.test/arucon/profile')]){const s=sw();let called=false;s.events.fetch({request:r,respondWith:()=>called=true});assert.equal(called,false)}});
test('Worker has no analytics, push, game clock or balance mutation',()=>{for(const s of ['localStorage','expMicro','MealEvent','setInterval(','pushManager'])assert(!source.includes(s));assert(!source.includes('__BUILD_HASH__'))});
